# ADVERTENCIA:
# Cualquier cambio en este archivo requiere que se vuelva a generar el arhivo de secretos .drone.sec leer el README.md para saber como hacerlo.

publish:
  condor:
    image: plugins/drone-terraform
    # plan: true
    sensitive: true
    remote:
      backend: S3
      config:
        bucket: $$TERRAFORM_BUCKET
        key: terraform/condor.$$BRANCH.tfstate
        region: $$AWS_DEFAULT_REGION
        access_key: $$AWS_ACCESS_KEY_ID
        secret_key: $$AWS_SECRET_ACCESS_KEY
    vars:
      aws_access_key: $$AWS_ACCESS_KEY_ID
      aws_secret_key: $$AWS_SECRET_ACCESS_KEY
      aws_region: $$AWS_DEFAULT_REGION
      branch: $$BRANCH
    root_dir: apps/condor
